version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: backend
    volumes:
      - ./backend/:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    restart: always

volumes:
  db:
    external: false
